[project]
name = "example-tools"
authors = ["Scott Persinger <scottpersinger@gmail.com>"]
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.11"
dependencies = [
    "httpx >= 0.28.1",
    "googlenewsdecoder >= 0.1.7",
    "google-news-feed >= 1.1.0",
    "html2text >= 2024.2.26",
    "pandas >= 2.2.3",
    "pytest",

]
